spring.application.name=foddiesapi

#mongodb configuration.
spring.data.mongodb.uri=mongodb+srv://mohiraja2023_db_user:ai3tPQqOzXvG9oat@cluster0.7tzpzn6.mongodb.net/ayurvedicproducts?retryWrites=true&w=majority&appName=Cluster0
#mohiraja2023_db_user

#aws s3 configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

jwt.secret.key=${JWT_SECRET_KEY}
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}